# Generated by Django 5.2.3 on 2025-08-05 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(default='Received', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('service_type', models.CharField(choices=[('custom_orders', 'Custom Ice Cream Orders'), ('bulk_orders', 'Franchise and Bulk Orders'), ('event_catering', 'Event Catering'), ('birthday_parties', 'Birthday Parties'), ('corporate_events', 'Corporate Events'), ('wedding_catering', 'Wedding Catering')], max_length=50)),
                ('event_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('budget_range', models.CharField(choices=[('under_5000', 'Under ₹5,000'), ('5000_15000', '₹5,000 - ₹15,000'), ('15000_30000', '₹15,000 - ₹30,000'), ('30000_50000', '₹30,000 - ₹50,000'), ('above_50000', 'Above ₹50,000')], max_length=20)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.PositiveIntegerField()),
                ('items_summary', models.TextField(default='')),
                ('status', models.CharField(default='Delivered', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_number'],
                'unique_together': {('user', 'order_number')},
            },
        ),
    ]
